stages:
  - test

test:
  stage: test
  image: python:3.9
  before_script:
    - export PYTHONPATH=$PYTHONPATH:/builds/diegargon/monnet-ansible/src
    - pip install -r requirements.txt
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
  script:
    - pytest -v tests/test_monnet_ansible.py

