stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  before_script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - sleep 5 # Trying avoid dns resolution problems
    - export PYTHONPATH=$PYTHONPATH:/builds/diegargon/monnet-ansible/src
    - pip install -r requirements.txt
    
  script:
    - pytest -v tests/test_monnet_ansible.py

deploy_to_github:
  stage: deploy
  image: alpine/git
  script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - sleep 5 # Trying avoid dns resolution problems
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"    
    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-ansible.git
    - git remote -v
    - git fetch github main
    - git checkout -b main || git checkout main    
    - git pull --rebase --strategy=recursive --strategy-option=theirs github main || true
    - git add .
    - git commit -m "Deploy changes from GitLab CI" || echo "Nothing to commit"
    - git push -u github main