stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  before_script:
    - export PYTHONPATH=$PYTHONPATH:/builds/diegargon/monnet-ansible/src
    - pip install -r requirements.txt
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
  script:
    - pytest -v tests/test_monnet_ansible.py

deploy_to_github:
  stage: deploy
  image: alpine/git
  script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - ls -al 
    - pwd
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"
    - git init
    - ls -al 
    - git add .
    - git commit -m "Deploy changes from GitLab CI"

    # Configurar el repositorio remoto
    #- git remote add origin https://oauth2:${GITHUB_TOKEN}@github.com/<usuario>/<repositorio>.git

    # Subir los cambios a la rama principal o la deseada
    #- git push -u origin main