stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  before_script:
    - export PYTHONPATH=$PYTHONPATH:/builds/diegargon/monnet-ansible/src
    - pip install -r requirements.txt
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
  script:
    - pytest -v tests/test_monnet_ansible.py

deploy_to_github:
  stage: deploy
  image: alpine/git
  script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - ls -al 
    - pwd
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"
    - git init    
#    - git remote add origin https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-ansible.git
    - git remote set-url origin https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-ansible.git
    - git remote -v
    - git fetch origin main
    - git checkout -b main || git checkout main    
    - git add .
    - git commit -m "Deploy changes from GitLab CI"
    - git push -u origin main