- name: Gather iptables facts
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Get iptables facts
      iptables_facts:

    - name: Show iptables facts
      debug:
        msg: "{{ ansible_iptables }}"
