- name: Gather service facts
  hosts: all
  tasks:
    - name: Gather facts about services
      service_facts:

    - name: Show all service facts
      debug:
        msg: "{{ ansible_services }}"
