- name: Shutdown a Linux system
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Shutdown the system
      command: shutdown -h now
      register: shutdown_result
      ignore_errors: yes

    - name: Check if the shutdown command was executed
      debug:
        msg: "Shutdown command was executed successfully."
      when: shutdown_result.rc == 0

    - name: Report error if the shutdown command failed
      debug:
        msg: "Shutdown command failed or the system is still running."
      when: shutdown_result.rc != 0