- name: Shutdown a Linux system
  hosts: all
  become: yes
  gather_facts: false
  tasks:
      - name: Ensure only one host is being managed
        fail:
          msg: "This playbook must be run on exactly one host."
        when: groups['all'] | length != 1

    - name: Shutdown the system
      command: shutdown -h now
      register: shutdown_result
      async: 1
      poll: 0
